// One-shot generator. Run once; do not print keys in chat. Output: src/keys.ts
import { createHash, randomInt } from "node:crypto";
import { writeFileSync } from "node:fs";

const LETTERS = "ABCDEFGHJKLMNPQRSTUVWXYZ"; // no I/O to avoid confusion with 1/0
const LEVELS = ["N4", "N3", "N2", "N1"];
const MASK = randomInt(1, 255);

function key() {
  return Array.from({ length: 4 }, () => LETTERS[randomInt(LETTERS.length)]).join("");
}
function sha256(s) {
  return createHash("sha256").update(s).digest("hex");
}
function obfuscate(s) {
  return Array.from(s, (c) => (c.charCodeAt(0) ^ MASK).toString(16).padStart(2, "0")).join("");
}

const used = new Set();
const entries = LEVELS.map((level) => {
  let k = key();
  while (used.has(k)) k = key();
  used.add(k);
  return { level, hash: sha256(k), obf: obfuscate(k) };
});

const ts = `// GENERATED by scripts/gen-keys.mjs. Do not edit by hand.
import type { Level } from "./types";

const MASK = ${MASK};
const ENTRIES: ReadonlyArray<{ level: Level; hash: string; obf: string }> = ${JSON.stringify(entries, null, 2)};

async function sha256Hex(s: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(buf), (b) => b.toString(16).padStart(2, "0")).join("");
}

/** Returns the level a key unlocks, or null when invalid. Case-insensitive. */
export async function verifyKey(input: string): Promise<Level | null> {
  const h = await sha256Hex(input.trim().toUpperCase());
  return ENTRIES.find((e) => e.hash === h)?.level ?? null;
}

/** Returns the key that unlocks \`level\`, or null for N5. */
export function revealKey(level: Level): string | null {
  const e = ENTRIES.find((x) => x.level === level);
  if (!e) return null;
  const bytes = e.obf.match(/../g) ?? [];
  return bytes.map((b) => String.fromCharCode(parseInt(b, 16) ^ MASK)).join("");
}
`;
writeFileSync(new URL("../src/keys.ts", import.meta.url), ts);
console.log("src/keys.ts written for", LEVELS.join(", "));
