// GENERATED by scripts/gen-keys.mjs. Do not edit by hand.
import type { Level } from "./types";

const MASK = 62;
const ENTRIES: ReadonlyArray<{ level: Level; hash: string; obf: string }> = [
  {
    "level": "N4",
    "hash": "f5200e7f412961e75859dd76770a813f82d368f3f4c3192acdc3f832dda28efd",
    "obf": "6a76676c"
  },
  {
    "level": "N3",
    "hash": "69fbe09a9514a35cc84f5c31fda28fbb5c2867be4c86a560d89968f8c3638254",
    "obf": "7b6c7366"
  },
  {
    "level": "N2",
    "hash": "bac440ce702247944a9ab2dd1f9f1fb9162daf900425c0adf20986a9441b53a9",
    "obf": "7c7b7378"
  },
  {
    "level": "N1",
    "hash": "4154f86d404450a2a75b0b5be8796d58d881c1184b06f426687f1a56fe92471a",
    "obf": "6a7b696e"
  }
];

async function sha256Hex(s: string): Promise<string> {
  const buf = await crypto.subtle.digest("SHA-256", new TextEncoder().encode(s));
  return Array.from(new Uint8Array(buf), (b) => b.toString(16).padStart(2, "0")).join("");
}

/** Returns the level a key unlocks, or null when invalid. Case-insensitive. */
export async function verifyKey(input: string): Promise<Level | null> {
  const h = await sha256Hex(input.trim().toUpperCase());
  return ENTRIES.find((e) => e.hash === h)?.level ?? null;
}

/** Returns the key that unlocks `level`, or null for N5. */
export function revealKey(level: Level): string | null {
  const e = ENTRIES.find((x) => x.level === level);
  if (!e) return null;
  const bytes = e.obf.match(/../g) ?? [];
  return bytes.map((b) => String.fromCharCode(parseInt(b, 16) ^ MASK)).join("");
}
